### ISSUE TITLE
bslib navigation tabs - malfunctioning tab-index

### ISSUE THREAD

**Issue by csckata** [BioDT/biodt-shiny#101]

**Comment by csckata** [comment]
<img width="1440" alt="Screenshot 2024-09-12 at 7 47 47" src="https://github.com/user-attachments/assets/e45be530-7bba-4204-a724-5ab7c698bc73">
<img width="1438" alt="Screenshot 2024-09-12 at 7 47 14" src="https://github.com/user-attachments/assets/27c30bf6-4c79-458f-8558-41cc9332e8ac">

For some interesting reason, the tab order changes when going around the app. Active pages ignores (sets the tab-index to -1) main menu items, which isn't good if you're keyboard-only user.

**Comment by Nithador** [comment]
https://github.com/rstudio/bslib/issues?q=is%3Aissue++accessibility+
