### ISSUE TITLE
Beekeeper page check whether the simulation marker is intersecting with the input map

### ISSUE THREAD

**Issue by Nithador** [BioDT/biodt-shiny#33]
- [x] Send map() from honeybee_beekeeper_server module to beekepeer_map_server module
- [x] Create terra vect with these coordinates and project them into "EPSG:4326"
- [x] Beekeeper_map.R file - ObserveEvent(input$map_plot_draw_new_feature) - Check the coordinates() are in the map() with terra::extract()
- [x] If NA is in Category of the output set coordinates_text() to warning message that selected location is outside of the map and set out() to NULL

**Comment by osalamon** [comment]
It should be done.

![image](https://github.com/BioDT/biodt-shiny/assets/96975203/cbf24048-97d6-44f2-b8e1-1162b84ca527)

vs.

![image](https://github.com/BioDT/biodt-shiny/assets/96975203/03884423-0301-4e54-8e09-c36a3820caf4)


NOTE: in R terminal when using `terra::extract` there appears additional warning message `Warning: [extract] transforming vector data to the CRS of the raster`. I don't know how to disable the warning or whether it is desired to do so...
