### ISSUE TITLE
Beekeeper page - make the map location choosing more intuitive

### ISSUE THREAD

**Issue by csckata** [BioDT/biodt-shiny#54]
User comment:

I understood that I need to pick the pin icon and drop in the map, but this is not clear/intuitive in the GUI -> Could the map location choosing be made so, that the user does not need to click the icon first and then the map but to click the map right away?

**Comment by sharifX** [comment]
+1
I also had the same issue.  And also the icon is not the first thing I notice. 

One option could be to include an image of the placement icon in the instruction text, next to the "Select point on the map by first clicking the placement icon" line so users know which icon it is referring to.
