### ISSUE TITLE
Warning: app/data/honeybee/map.tif: No such file or directory (GDAL error 4)

### ISSUE THREAD

**Issue by simonrolph** [BioDT/biodt-shiny#60]
Hello, trying to get back into developing the cultural ecosystem services module for the app. I followed the readme, downloaded the data putting it in the `local_data` folder. But the code is looking for `app/data/honeybee/map.tif:`. Is the readme out of date?

I also notice that installing renv, activating and restoring from lockfile is not in the readme.

**Comment by Nithador** [comment]
Hi, there were mistakes in the readme. I try to sort out at least some of them. data should be in `app/data` folder

**Comment by simonrolph** [comment]
Yes that sorts out the issue, thanks
