### ISSUE TITLE
better naming convention for output.csv

### ISSUE THREAD

**Issue by sharifX** [BioDT/biodt-shiny#63]
To avoid output.csv output (1).csv situation, use a file naming convention to ensure that the output file has an unambiguous name.

you could add timestamp, uuid, the app, project, run name etc.

**Comment by simonrolph** [comment]
Sounds like a sensible suggestion, which pDT is this for specifically? Are there any FAIR compliant guidelines for file naming schemas we could follow?

**Comment by sharifX** [comment]
I was trying the "Honeybee Beekeeper Case". 

There's no specific FAIR guidelines on this. But I think we can apply a consistent approach for all the pDTs. 

This has some nice tips: https://howto.lcsb.uni.lu/integrity/naming/. 

Maybe something like this (make sure to not allow spaces-> "Honeybee_Beekeeper_Case"  instead of "Honeybee Beekeeper Case" for example):

shortpDTname_runN_date-timestamp.csv 
or 
shortpDTname_runN_uuid.csv

**Comment by Nithador** [comment]
Hi, we updated the naming to 

shortpDTname_runN_date-timestamp.csv

#aa08a9af556ec61721fc1496a2190218678a3c53
#6e4775b2fd58e7248ecc599e7e175856e4341753
