### ISSUE TITLE
prepare Wild Boar Disease

### ISSUE THREAD

**Issue by osalamon** [BioDT/biodt-shiny#95]
- prepare Rhino BioDT app for Wild Boar Disease pDT
- there're 2 maps to load
- possible to switch to one, or another > show the chosen map on FE

**Comment by osalamon** [comment]
Hi @Nithador ,

unfortunately, I give up on https://github.com/BioDT/biodt-shiny/tree/95-prepare-wild-boar-disease 

Checboxes handling show/remove layers (that .tif data files) work only partially fine.

I am not able to make a logic of showing/removing map's layers working. If you find some spare time, please, can you show me how to do it properly? It seems to me that I tried absolutely everything but nothing worked. I tried something, but that resulted in breaking some other thing, and vice versa. I'll be happy very much to have this one finished in satisfactory manner.

**Comment by Nithador** [comment]
Instead of making logic outside of  leaflet, use leaflet[addRasterImage, addLegend, addTiles, addLayersControl)]

After that, add shiny[fileInput] to upload a new file for input layer (the whole europe raster), for that You should use leafletproxy

see [app/logic/honeybee/honeybee_beekeeper_map.R](app/logic/honeybee/honeybee_beekeeper_map.R)
and [app/view/ces/ces_rp_biodiversity.R](app/view/ces/ces_rp_biodiversity.R

**Comment by osalamon** [comment]
Ok, I was somehow able to get up and running both things we agreed upon, ie.: 1) switch controls for changing layers inside Leaflet map itself; 2) a possibility to upload file (.tif) and render it on the map.

Viz screenshots below:
![image](https://github.com/user-attachments/assets/33f2e439-42c6-4a79-b1c8-f1d93058b4ab)
![image](https://github.com/user-attachments/assets/c0a9520d-c0d5-446e-bfec-76516a8ab9c4)
![image](https://github.com/user-attachments/assets/022092ca-c556-4e64-89df-f1be45bd164c)

I am sure that there will be additional need to edit/tune what is there. Let's do it step by step. It is not final version but at least in principle I was able to do what you wanted:-)

If you have spare time, you can check (and/or) code review here: https://github.com/BioDT/biodt-shiny/tree/95-prepare-wild-boar-disease
